### ISSUE TITLE
Add Method for Distance

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#11]
This is sort of follow up from https://github.com/Segelzwerg/SportToolBox/issues/7#issuecomment-543224311

Distances should be able to be add. These should also handle an overflow in meter. Therefor it needs a new method for handling the overflow. By implementing this, the constructors can be refractored.

- [ ] add takes a another Distance and returns a new one
- [ ] overflow handles input for meters greater than 1000. It returns a new Distance instance, too.

**Comment by Sri-V** [comment]
Hi Can i work on this?

**Comment by Segelzwerg** [comment]
Yes of course.

**Comment by Segelzwerg** [comment]
This is closed by #12
