### ISSUE TITLE
Add Pace Calculator to SpeedCalculator

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#15]
Add a method that calculates the time need for travelling a given Distance. There are two standard units in the metric system: min/km and min/100m.

- [ ] computePace() returns a Pace Instance
- [ ]  Add Pace in IUnits
- [ ]  Add inMinutesPerKilometer() to Pace
- [ ]  Add inMinPerHundredMeters() to Pace

**Comment by GledsonAfonso** [comment]
Can I try this?

**Comment by Segelzwerg** [comment]
yes, and thank you for contributing.
