### ISSUE TITLE
Unit Conversion for Speed

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#16]
There are many more speed units than km/h (kph). So Speed should become an interface from which we inherit different speeds units. Each Unit should have methods for converting it to the other units.

Units to add:
- [x]  meter per second

- [x]  miles per hour

- [x]  knots (nautical miles per hour)

Please feel free to suggest other units I forgot.

**Comment by retsbol** [comment]
Could I try this one as well?
