### ISSUE TITLE
Add Tests for new Speed Units

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#18]
#17 added units
We should implement some test

- [x] conversion itself

- [x] speed calculator

- [x] invalid input

**Comment by Jataki** [comment]
Hi! Can I take this?

**Comment by Segelzwerg** [comment]
yes, thank you very much.

**Comment by katsadim** [comment]
I know that this was taken, but I couldn't resist. Sorry @Jataki

**Comment by Segelzwerg** [comment]
@katsadim  thank you very much
Previously I forgot to ask for test for invalid input. So I reopened.

**Comment by Jataki** [comment]
Not cool @katsadim ahahah no problem.

**Comment by katsadim** [comment]
thanks for the understanding @Jataki . I will leave the invalid input to you :)
