### ISSUE TITLE
JavaDoc Implementation

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#21]
Add javadoc to gradle so it creates doc page:

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html

**Comment by qzxclkj** [comment]
Mind if I take this one?

**Comment by Segelzwerg** [comment]
Not at all, glad if you would do it.

**Comment by qzxclkj** [comment]
Here's the [PR #26](https://github.com/Segelzwerg/SportToolBox/pull/26)

**Comment by Segelzwerg** [comment]
thank you very much
