### ISSUE TITLE
Add Usage to read.md

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#29]
Start a usage section for read.md

- [x] Describe how to use the website - there is only one function for now.

- [ ] Describe how to install and run it locally.

**Comment by An0u** [comment]
Anyone working on this? I'd like to take it up.

**Comment by Segelzwerg** [comment]
The part of the local installment is still up for grabs.

**Comment by Segelzwerg** [comment]
solved by 28c787d1f6f6cb2b6f44e8f2d9b74f91caf7f2c1
