### ISSUE TITLE
Add Tests for Distance

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#6]
The distance class should be able to handle meters as well. These means the Speed Class must be updated as well.

- [x] test for method that  regulates overflow if meter input is greater than 1000
- [x] test for computeSpeed(). This can be very similar to the ones in SpeedCalculator
- [x] Test for invalid input e.g. negative distance

**Comment by rods-honorio** [comment]
can i get this one? :D

**Comment by Segelzwerg** [comment]
yes sure. I just did one test, in order to check, if I can approve another PR. But the others are still up for graps.

**Comment by rods-honorio** [comment]
Hello :) i apologize for the delay. How specifcally would be the approach to implement the "greater than zero" validation? It seems to envolve a little more than the issue scope. Justt added a test for the distance class, feel free to answer in my PR.

**Comment by Segelzwerg** [comment]
No worries rod, we have all things to do beside coding open source.
The test for speed looks good.
I thought a little about your suggestion. Indeed there are some things we need to test for and implement into Distance Class as well, because we need something that throws an exception which we then can test if it's thrown correctly. But for the moment I can not think of a different invalid input other than negative numbers, which is not handle by Java itself. Like trying to construct with a String. But feel free to comment on it what you had in mind.
If you would like you can work on that or I will mark as as not taken.
