### ISSUE TITLE
Add Test for Time

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#8]
The time should deal with minutes and seconds. These means the Speed Class must be updated as well.

- [x] test for method that  regulates overflow if seconds is greater than 60 and if minutes are greater than 60 
- [x] test for computeSpeed(). This can be very similar to the ones in SpeedCalculator
- [x] Test for invalid input e.g. negative values

**Comment by mkmaier** [comment]
I hope this is about what you had in mind :)

**Comment by Segelzwerg** [comment]
yes almost, I commented on the PR. #13

**Comment by Segelzwerg** [comment]
@mkmaier thx for your contributions

**Comment by mkmaier** [comment]
@Segelzwerg You're very welcome, I enjoyed it!
