### ISSUE TITLE
Remove Sneaky-Throw Annotations from tests

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#92]

**Comment by EEM86** [comment]
@Segelzwerg hello, creating PR for develop branch. Should I work with other branches in the scope of this task?

**Comment by Segelzwerg** [comment]
@EEM86 develop is fine! thank you very much. I'll have a look into PR.

**Comment by EEM86** [comment]
@Segelzwerg hi, should I add something? Seems PR was approved and merged.

**Comment by Segelzwerg** [comment]
No simply forgot to close.
